[package]
name = "lib_spearman"
version = "0.1.0"
authors = ["finben <benfindeisen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
